### ISSUE TITLE
blank DB?

### ISSUE THREAD

**Issue by mgaulton** [reuteras/docker-kippo#1]
I've followed the directions correctly but i'm wondering why nothing seems to be written to the DB. kippo-graph is finding nothing. I do see connections to it from what i can tell. Any suggestions on troubleshooting this?
note: i used iptables natting rules to redirect badactor IPs to the kippo instance.

docker run --name kippodb -e MYSQL_ROOT_PASSWORD="pass" -d mysql:latest
docker run -p 22222:22 --name kippo --link kippodb:mysql -d reuteras/docker-kippo
docker run -p 8000:80 --name kippo-graph --link kippodb:mysql -d reuteras/docker-kippo-graph

**Comment by mgaulton** [comment]
and I may have answered my own question. i had a mysql instance on the host machine, I've disabled that to see if it was a port conflict.

**Comment by mgaulton** [comment]
That does not appear to be the case

**Comment by mgaulton** [comment]
2015-11-04 18:58:46,951 INFO waiting for kippo to die
2015-11-04 18:58:47,004 INFO stopped: kippo (exit status 0)
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
ERROR 2003 (HY000): Can't connect to MySQL server on 'mysql' (111)
2015-11-04 18:58:58,421 CRIT Supervisor running as root (no user in config file)
2015-11-04 18:58:58,423 INFO supervisord started with pid 1
2015-11-04 18:58:59,426 INFO spawned: 'kippo' with pid 30
2015-11-04 18:59:00,427 INFO success: kippo entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                   NAMES
5e0157cc2e65        reuteras/docker-kippo-graph   "/entrypoint.sh /usr/"   About an hour ago   Up 2 minutes        0.0.0.0:8000->80/tcp    kippo-graph
c50daf75d6d1        reuteras/docker-kippo         "/entrypoint.sh /usr/"   About an hour ago   Up 2 minutes        0.0.0.0:22222->22/tcp   kippo
117b6871cc1d        mysql:latest                  "/entrypoint.sh mysql"   About an hour ago   Up 2 minutes        3306/tcp                kippodb

**Comment by reuteras** [comment]
I'll take a look at this as soon as possible but unfortunately I'm fully booked until the weekend.

**Comment by mgaulton** [comment]
No worries, i'm not in a rush.

**Comment by reuteras** [comment]
Finally had time to test this and my results are:

sudo docker run --name kippodb -e MYSQL_ROOT_PASSWORD="pass" -d mysql:latest
sudo docker run -p 22222:22 --name kippo --link kippodb:mysql -d reuteras/docker-kippo
ssh -p 22222 root@localhost
# tried some passwords
sudo docker exec kippodb mysql --password=pass kippo -e "select * from auth;"
mysql: [Warning] Using a password on the command line interface can be insecure.
id	session	success	username	password	timestamp
1	1e457d7e865111e5afbf0242ac110002	0	root	test	2015-11-08 19:44:29
2	1e457d7e865111e5afbf0242ac110002	0	root	test123	2015-11-08 19:44:32
3	1e457d7e865111e5afbf0242ac110002	0	root	test123!	2015-11-08 19:44:35
4	1e457d7e865111e5afbf0242ac110002	0	root	Password	2015-11-08 19:44:47
5	1e457d7e865111e5afbf0242ac110002	0	root	Password!	2015-11-08 19:44:56

Your running processes looks correct as far as I can see. Can you connect to your mysql database from your host?

**Comment by mgaulton** [comment]
docker exec kippodb mysql --password=pass kippo -e "select * from auth;"

running your command line there gives me 61 lines.

**Comment by reuteras** [comment]
Ok, then there is a problem in my kippo-graph. Is there graphs on any page of the pages?

**Comment by reuteras** [comment]
Finally had some more time and found the real problem. There seems to be a problem in kippo-graph when used with MySQL 5.7 which now is MySQL latest. Updated README to specify that MySQL 5.6 should be used instead (which I should have done from the beginning).

**docker run --name kippodb -e MYSQL_ROOT_PASSWORD="pass" -d mysql:5.6**

**Comment by mgaulton** [comment]
coool. thanks.
